#!/usr/bin/env python3
"""
Cut Bootstrap Icons down to the ones this shop actually uses.

The full set is about two thousand glyphs: a 131 KB font and a stylesheet of
rules for every one of them, downloaded on every page so that forty of them can
be drawn. This reads the icons out of the templates and the scripts, keeps those
and nothing else, and writes a stylesheet and a font beside each other.

Run it after adding an icon to a template:

    python3 tools/subset-icons.py

A test guards it: any icon used but missing from the subset fails the suite,
rather than showing an empty box on a shopkeeper's screen.
"""
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
UPSTREAM = ROOT / "node_modules" / "bootstrap-icons" / "font"
OUT_CSS = ROOT / "resources" / "scss" / "_icons.scss"
OUT_FONT = ROOT / "resources" / "fonts" / "bootstrap-icons-subset.woff2"

SEARCH = [ROOT / "resources" / "views", ROOT / "resources" / "js", ROOT / "app"]


# Icons whose name is decided by a ternary inside the class attribute, where
# there is no literal to find. Both halves of each choice.
ALWAYS = {
    "arrow-left", "arrow-right",        # the back link, which mirrors in RTL
    "sun", "moon-stars", "circle-half",  # the theme switch
}

PATTERNS = [
    # <i class="bi bi-trash">
    r"\bbi-([a-z0-9-]+)",
    # 'icon' => 'box-seam' in a PHP array, and icon="box-seam" on a component
    r"""['"]?icon['"]?\s*(?:=>|=|:)\s*['"]([a-z0-9-]+)['"]""",
]


def used():
    """
    Every icon this shop can draw.

    Not just the ones written out in full: the sidebar, the dashboard and the
    search results all take their icon from a PHP array, and the empty state
    takes it from a prop, so the name never appears next to "bi-" anywhere.
    Miss one and it does not break — it draws an empty box, which is worse.
    """
    names = set(ALWAYS)

    for base in SEARCH:
        for path in base.rglob("*"):
            if not path.is_file() or path.suffix not in {".php", ".js"}:
                continue

            text = path.read_text("utf8", errors="ignore")

            for pattern in PATTERNS:
                names |= set(re.findall(pattern, text))

    # "bi" itself is the base class. A trailing hyphen is the front half of a
    # name that an interpolation finished — bi-arrow-{{ ... }} — and ALWAYS
    # above carries whatever those can turn into.
    return {n for n in names if n and n != "bi" and not n.endswith("-")}


def codepoints():
    css = (UPSTREAM / "bootstrap-icons.css").read_text("utf8")
    found = {}
    for name, point in re.findall(r'\.bi-([a-z0-9-]+)::before\s*\{\s*content:\s*"\\([0-9a-fA-F]+)"', css):
        found[name] = point
    return found


def main():
    names = used()
    points = codepoints()

    missing = sorted(n for n in names if n not in points)
    keep = sorted(n for n in names if n in points)

    if missing:
        print("These are written as icons but are not in Bootstrap Icons:", file=sys.stderr)
        for n in missing:
            print("  bi-" + n, file=sys.stderr)

    OUT_FONT.parent.mkdir(parents=True, exist_ok=True)

    unicodes = ",".join("U+" + points[n] for n in keep)

    subprocess.run([
        sys.executable, "-m", "fontTools.subset",
        str(UPSTREAM / "fonts" / "bootstrap-icons.woff2"),
        "--unicodes=" + unicodes,
        "--flavor=woff2",
        "--output-file=" + str(OUT_FONT),
    ], check=True)

    rules = "\n".join(
        '.bi-%s::before { content: "\\%s"; }' % (n, points[n]) for n in keep
    )

    OUT_CSS.write_text(f"""// GENERATED by tools/subset-icons.py — do not edit by hand.
//
// Only the {len(keep)} icons this shop uses. The full set is about two thousand,
// which is a 131 KB font and a rule for every one of them on every page.
//
// Add an icon to a template and this file will not know about it: the test
// IconSubsetTest fails and tells you to run the script again.

@font-face {{
  font-family: 'bootstrap-icons';
  font-display: block;
  src: url('../fonts/bootstrap-icons-subset.woff2') format('woff2');
}}

.bi::before,
[class^='bi-']::before,
[class*=' bi-']::before {{
  display: inline-block;
  font-family: 'bootstrap-icons' !important;
  font-style: normal;
  font-weight: normal !important;
  font-variant: normal;
  text-transform: none;
  line-height: 1;
  vertical-align: -.125em;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}}

{rules}
""", "utf8")

    print(f"kept {len(keep)} icons")
    print(f"  {OUT_CSS.relative_to(ROOT)}")
    print(f"  {OUT_FONT.relative_to(ROOT)}  {OUT_FONT.stat().st_size // 1024} KB")


if __name__ == "__main__":
    main()
